spring:
  datasource: #default
    url: jdbc:oracle:thin:@172.16.241.111:5211:TMUXDB
    username: mxacc_dev1
    password: "{cipher}3f84fc951e629b47b9d560a2ac15cef5e866b0b9a2e958008be4d5503da03f1d"
  
      
  jpa:
    show-sql: true
  cloud:
    consul:   
      enabled: false
      host: localhost   #Consul service register server address
      port: 8500        #Consul service register server port
      discovery:
        ipAddress: localhost  #your service discovery address(where it running)
        acl-token: 53fd315c-0ffb-d2b9-ac7d-532e11eb567f
        #以下為了測試, 因防火牆測試機註冊service無法打到個人開發機, 拿別人的healthCheck
        #healthCheckUrl: http://172.16.241.85:8085/X-Tech-Test/api/Health
    
security:
  needAuthenticated: false

